/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.seminar;

import org.junit.Test;

import static org.junit.Assert.*;

public class ExampleTest {
    /**
     * テストされる関数
     * @param a 第一引数
     * @param b 第二引数
     * @return 第一引数と第二引数の和
     */
    public int example(int a, int b) {
        return a+ b;
    }

    /**
     * テストを実行する関数
     * assertEquals ... 後ろの２つの引数が等しければテスト成功、異なればエラーになる関数
     */
    @Test
    public void testExample() {
        int expected = 5;
        int actual = example(2, 3);
        assertEquals("引数2と3を足して結果5を返す", expected, actual);
    }
}
