/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.seminar;

public class App {
    public static int[] calculate(int[] seiseki) {
        int kyouyou = seiseki[0];
        int daiichiMajor = seiseki[1];
        int dainiMajor = seiseki[2];
        int sonotaMajor = seiseki[3];
        int jiyuu = seiseki[4];
        return new int[]{kyouyou, daiichiMajor, dainiMajor, sonotaMajor, jiyuu};
    }

    public static void main(String[] args) {
        int[] seiseki = {30, 24, 32, 16, 14, 8};
        seiseki = calculate(seiseki);
        for (int i = 0; i < seiseki.length; i++) {
            System.out.print(seiseki[i] + " ");
        }
    }
}
