/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.seminar;

public class App {
    /**
     * 卒業要件
     */
    protected static final int[] SOTSUGYO_YOUKEN = new int[]{30, 24, 32, 16, 14, 8};

    /**
     * @param tanni 取得単位数の整数配列。
     *              new int[6]{教養, 基礎, 第一メジャー, 第二メジャー, その他メジャー, 自由選択}
     * @return 卒業要件に照らして余剰分を調整した単位数の整数配列
     * - 第一メジャー、第二メジャーの余剰はその他メジャーに入る
     * - 教養、基礎、その他メジャーの余剰は自由選択に入る
     */
    public static int[] calculate(int[] tanni) {
        int kyouyou = tanni[0];
        int kiso = tanni[1];
        int daiichiMajor = tanni[2];
        int dainiMajor = tanni[3];
        int sonotaMajor = tanni[4];
        int jiyuu = tanni[5];
        //
        // このメソッド(関数)を編集してください
        //
        return new int[]{kyouyou, kiso, daiichiMajor, dainiMajor, sonotaMajor, jiyuu};
    }

    public static void main(String[] args) {
        int[] seiseki = {30, 24, 32, 16, 14, 8};
        seiseki = calculate(seiseki);
        for (int i = 0; i < seiseki.length; i++) {
            System.out.print(seiseki[i] + " ");
        }
    }
}
