/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.seminar;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        assertNotNull("calculate関数が呼び出し可能", App.calculate(new int[]{0, 0, 0, 0, 0}));
    }
}
