/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.seminar;

public class App {
    public static void main(String[] args) {
        int[] seiseki = {32, 24, 32, 16, 14, 8};
        System.out.print("計算前: ");
        printArray(seiseki);
        System.out.print("計算後: ");
        printArray(Calculator.calculate(seiseki));
    }

    public static void printArray(int[] array) {
        for (int i = 0; i < array.length; i++) {
            System.out.print(array[i] + " ");
        }
        System.out.print("\n");
    }
}
